### ISSUE TITLE
Understanding the performance numbers of HERD

### ISSUE THREAD

**Issue by karthikrish9** [efficient/rdma_bench#1]
Hi @anujkaliaiitd 

I am trying to understand the performance numbers printed out by the HERD server and client. Could you please help? thank you so much.

Server prints:
```
main: Worker 0: 3269603.08 IOPS. Avg per-port postlist = 1.00. HERD lookup fail rate = 0.0085
main: Worker 0: 3269148.67 IOPS. Avg per-port postlist = 1.00. HERD lookup fail rate = 0.0085
main: Worker 0: 3228738.91 IOPS. Avg per-port postlist = 1.00. HERD lookup fail rate = 0.0085
main: Worker 0: 3268642.09 IOPS. Avg per-port postlist = 1.00. HERD lookup fail rate = 0.0085
```

Client prints:
```
main: Client 0: 3252758.84 IOPS. nb_tx = 1301282816
main: Client 0: 3274758.97 IOPS. nb_tx = 1301807104
main: Client 0: 3267195.87 IOPS. nb_tx = 1302331392
main: Client 0: 3259528.61 IOPS. nb_tx = 1302855680
```
So what is the throughput here?  3 Million input output  operations per second? 
Is it normal? Or I am running it with a wrong configuration? Thank you so much for 
your time. 

I am running server (8 core machine with RDMA NIC) on a machine with following config:
```

blue "Reset server QP registry"
sudo killall memcached
memcached -l 0.0.0.0 1>/dev/null 2>/dev/null &
sleep 1

blue "Starting master process"
sudo LD_LIBRARY_PATH=/usr/local/lib/ -E \
        numactl --cpunodebind=0 --membind=0 ./main \
        --master 1 \
        --base-port-index  0 \
        --num-server-ports 1 &

# Give the master process time to create and register per-port request regions
sleep 1

blue "Starting worker threads"
sudo LD_LIBRARY_PATH=/usr/local/lib/ -E \
        numactl --physcpubind=0,2,4,6 --membind=0 ./main \
        --is-client 0 \
        --base-port-index 0 \
        --num-server-ports 1 \
        --postlist 1 &
```
Client (8 core machine with RNIC ) start script:
```
num_threads=1           # Threads per client machine
: ${HRD_REGISTRY_IP:?"Need to set HRD_REGISTRY_IP non-empty"}

blue "Running $num_threads client threads"

sudo LD_LIBRARY_PATH=/usr/local/lib/ -E \
        numactl --cpunodebind=0 --membind=0 ./main \
        --num-threads $num_threads \
        --base-port-index 0 \
        --num-server-ports 1 \
        --num-client-ports 1 \
        --is-client 1 \
        --update-percentage 0 \
        --machine-id $1 &

```
Running server and client:
```

./run-server.sh
./run-machine 0
```

**Comment by anujkaliaiitd** [comment]
Hi @karthikrish9.

This looks normal. You're running one client thread, which is getting 3.2 million GETs/sec. You can get higher throughput by using more client threads and/or client machines. You can also try increasing the number of worker threads at the server.

**Comment by karthikrish9** [comment]
Hi @anujkaliaiitd ,  

Thank you for the quick response.  I just tired to increase the worker count and client thread count; however, the throughput remains the same. Am I missing something? Thanks again.

Changes made in server program (Main.h):
```
#define MAX_SERVER_PORTS 4
#define NUM_WORKERS 4
#define NUM_CLIENTS 1
```

Changes made in  run-machine.sh
`
num_threads=14          # Threads per client machine`

However, the performance numbers remains the same. Please have a look at the following. 

Server side:
```

main: Worker 0: 1652370.54 IOPS. Avg per-port postlist = 1.00. HERD lookup fail rate = 0.0086
main: Worker 1: 1651721.62 IOPS. Avg per-port postlist = 1.00. HERD lookup fail rate = 0.0085
main: Worker 0: 1667000.01 IOPS. Avg per-port postlist = 1.00. HERD lookup fail rate = 0.0085
main: Worker 1: 1666686.36 IOPS. Avg per-port postlist = 1.00. HERD lookup fail rate = 0.0085
main: Worker 0: 1667554.10 IOPS. Avg per-port postlist = 1.00. HERD lookup fail rate = 0.0085
main: Worker 1: 1666986.13 IOPS. Avg per-port postlist = 1.00. HERD lookup fail rate = 0.0085
```
Client side:
```
main: Client 0: 3350052.09 IOPS. nb_tx = 482344960
main: Client 0: 3328939.28 IOPS. nb_tx = 482869248
main: Client 0: 3359242.83 IOPS. nb_tx = 483393536
main: Client 0: 3326507.02 IOPS. nb_tx = 483917824
main: Client 0: 3355742.99 IOPS. nb_tx = 484442112
main: Client 0: 3356828.98 IOPS. nb_tx = 484966400
```

**Comment by anujkaliaiitd** [comment]
The number of client threads also depends on setting `NUM_CLIENTS = 14`.

**Comment by karthikrish9** [comment]
Hi @anujkaliaiitd ,

But I have only one client machine, that is the problem. 

I have two more questions.  
1)  How do I measure  latency of HERD system using this repo? 
2)  Is there configurable variable to specify size of payload while measuring latency?

Thanks again

**Comment by anujkaliaiitd** [comment]
`NUM_CLIENTS` is the total number of client threads in the cluster (please see README.md), so you can run 14 client threads on one machine.

This version of HERD does not provide latency measurement, although it is not difficult to add that functionality.

`HERD_VALUE_SIZE` in `main.h` controls the size of values stored in the key-value store; key size is fixed at 16 bytes. If you increase `HERD_VALUE_SIZE`, you may also need to increase `HRD_MAX_INLINE` in `libhrd/hrd.h` so that the payload can be inlined in the work request. For best performance, `HRD_MAX_INLINE` should be set to the smallest possible value, i.e., `max(HERD_GET_REQ_SIZE, HERD_PUT_REQ_SIZE)`.

**Comment by karthikrish9** [comment]
Hi @anujkaliaiitd ,

As suggested I  increased the Worker count  and client count:

```
#define NUM_WORKERS  2
#define NUM_CLIENTS 70
```

Now server prints:
```

main: Worker 0: 5245347.70 IOPS. Avg per-port postlist = 1.00. HERD lookup fail rate = 0.0085
main: Worker 1: 5248653.92 IOPS. Avg per-port postlist = 1.00. HERD lookup fail rate = 0.0085
```

Does that mean throughput I am seeing now is `**10 Million operation/sec**`. Is this count additive?

**Comment by anujkaliaiitd** [comment]
Yes, the worker throughput is additive.
