### ISSUE TITLE
Failed to publish key server-0-0. Error A TIMEOUT OCCURRED, Reg IP= xx.xx.xx.xx

### ISSUE THREAD

**Issue by LiYuTingxxn** [efficient/rdma_bench#11]
Hello!  

I need your help. I set kRoCE = true, and use ROCEv2 protocol. I chaged "memcached -l 0.0.0.0 1>/dev/null 2>/dev/null" with "memcached -l 0.0.0.0 -u root -p 11266" in run_server.sh,  then run it. There a error: Failed to publish key server-0-0. Error A TIMEOUT OCCURRED, Reg IP= xx.xx.xx.xx. I have verified that the memcached is running successfully on the server by using telnet.  But it failed to run hrd_publish(). Can you tell me how to solve it.

Thank you very much!

**Comment by Bornedtobewilling** [comment]
@LiYuTingxxn Hi, I have encountered the same problem as yours. I am also using RoCE V2. Have you solved this problem? Thank you very much!
