### ISSUE TITLE
Herd tests error: ibv_post_send error Error 22

### ISSUE THREAD

**Issue by gaoning777** [efficient/rdma_bench#4]
For the herd tests, I'm having an issue on the client side, which returns "EINVAL" after calling ibv_post_send.

Server side program runs fine. And, I'm running 12 worker threads on the server and 2 client machines with 10 client threads in each machine.

Hardware: QLE7340 Infiniband single port.
OS: Ubuntu 14.04

Anyone has a clue?

**Comment by anujkaliaiitd** [comment]
QLogic NICs are currently unsupported by rdma_bench. This is primarily because these NICs lack userspace drivers, so I do not expect high performance.

**Comment by gaoning777** [comment]
Thanks, I'm right now running the tests with Mellanox MT27520.
However, a runtime error comes up as "HRD: Failed to modify QP to RTR" on both client and server side. The exact position is in libhrd/hrd_conn.c file function hrd_connect_qp, line number 462 and 483.

I've seen in http://www.rdmamojo.com/2013/01/12/ibv_modify_qp that says "When using RoCE, GRH must be configured.". Could this be the reason that obv_modify_qp returns false?

Thanks

**Comment by anujkaliaiitd** [comment]
Unfortunately, the HERD benchmark currently supports only InfiniBand.

I have ported some benchmarks in `rdma_bench` to C++. These benchmarks use `libhrd_cpp` instead of `libhrd`; `libhrd_cpp` supports RoCE. Porting the HERD code to use C++ and `libhrd_cpp` is straightforward, but not on my priority list. A PR is welcome :).

**Comment by gaoning777** [comment]
Thanks for your quick response.
I saw your ATC paper that you have been running your experiments on Emulab CX3. I'm also running on the cloudlab r320 machines, which seem to be the same machines. I compared the CPU version and NIC version.

Could it be that the HCI port is configured as Ethernet instead of Infiniband? Command " cat /sys/bus/pci/devices/0000\:09\:00.0/mlx4_port1" outputs "eth". I assume that the port being configured as "eth" means I'm using the RoCE instead of Infiniband, which is the reason that my herd tests are outputting errors.

Then, I tried "echo ib > /sys/bus/pci/devices/0000\:09\:00.0/mlx4_port1" but it  output "invalid argument". 

Do you possibly know where I could've done wrong?

**Comment by anujkaliaiitd** [comment]
It should work on Emulab CX3. Can you give me more details about your setup:

1. Which OS and device driver are you using?
2. Did you make any changes to HERD? A diff or link to a repo would useful.

**Comment by gaoning777** [comment]
Sorry, my mistake.
I accidentally input m510 in my cloudlab profile and I thought it was r320.
Luckily, it is running well.

Thanks a lot Anuj.
