### ISSUE TITLE
About Pliaf and FaRM

### ISSUE THREAD

**Issue by StarryVae** [efficient/rdma_bench#6]
I have read your HERD paper and you compared HERD with Pliaf and FaRM, could I take a look at the concrete implementation of GET operation in your emulating Pliaf  or FaRM? I would appreciate it if you would answer me.

**Comment by anujkaliaiitd** [comment]
It's in the Pilaf and FaRM branches of this repository: https://bitbucket.org/anujkaliaiitd/pingpong/src/master/
